안드로이드:
  - changed-files:
    - any-glob-to-any-file: 'apps/frontend/app/**'

IOS:
  - changed-files:
    - any-glob-to-any-file: 'apps/frontend/CashChatIOS/**'

BE:
  - changed-files:
    - any-glob-to-any-file: 'apps/backend/**'

FE:
  - changed-files:
    - any-glob-to-any-file: 'apps/frontend/**'

INFRA:
  - changed-files:
    - any-glob-to-any-file: 'infra/**'

문서:
  - changed-files:
    - any-glob-to-any-file: 'docs/**'

CICD:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

기능추가:
  - head-branch: ['^feature/', '^feat/']

버그수정:
  - head-branch: ['^fix/', '^bugfix/']

리펙토링:
  - head-branch: ['^refactor/']
