spring:

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: dev

  application.name: cash-chat-api

  h2.console.enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa

# O-Auth (Open Authorization)
oauth:
  registration:
    google-app:
      provider: google
      client-id: ${GOOGLE_CLIENT_ID:your-client-id}
      client-secret: ${GOOGLE_CLIENT_SECRET:your-client-secret}
      redirect-uri: http://localhost:8080/api/auth/callback/google
  provider:
    google:
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo


# JWT (JSON Web Token)
jwt:
  secret-key: ${JWT_SECRET:this-is-a-development-secret-key-at-least-32-bytes-long!!}
  # 30 (m) = 1,800 (s) = 1,800,000 (ms)
  access-token-expiry: 1800000
  # 14 (d) = 336 (h) = 20,160 (m) = 1,209,600 (s) = 1,209,600,000 (ms)
  refresh-token-expiry: 1209600000

